name: Comprobar tokens

on:
  push:

jobs:
  comprobar-token:
    runs-on: self-hosted
    env:
      DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
    steps:
      - name: Comprobar tokens
        shell: powershell
        run: |
          $localToken = [Environment]::GetEnvironmentVariable("LOCAL_DEV_TOKEN", "Machine")
          if ($env:DEV_TOKEN -eq $localToken) {
            Write-Host "Los tokens coinciden"
          } else {
            Write-Host "Los tokens NO coinciden"
            exit 1
          }
